In [13]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\kacpe\pycharmprojects\wizualizacjadanych\venv\lib\site-packages (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\kacpe\pycharmprojects\wizualizacjadanych\venv\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\kacpe\pycharmprojects\wizualizacjadanych\venv\lib\site-packages (from pandas) (1.20.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\kacpe\pycharmprojects\wizualizacjadanych\venv\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\kacpe\pycharmprojects\wizualizacjadanych\venv\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

WARNING: You are using pip version 21.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\users\kacpe\pycharmprojects\wizualizacjadanych\venv\scripts\python.exe -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
from typing import List, Dict
import numpy as np

In [167]:
movie

     Color;James Cameron;723.0;178.0;0.0;855.0;Joel David Moore;1000.0;760505847.0;Action|Adventure|Fantasy|Sci-Fi;CCH Pounder;Avatar;886204;4834;Wes Studi;0.0;avatar|future|marine|native|paraplegic;http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1;3054.0;English;USA;PG-13;237000000.0;2009.0;936.0;7.9;1.78;33000
0     Color;Gore Verbinski;302.0;169.0;563.0;1000.0;...
1     Color;Sam Mendes;602.0;148.0;0.0;161.0;Rory Ki...
2     Color;Christopher Nolan;813.0;164.0;22000.0;23...
3     ;Doug Walker;;;131.0;;Rob Walker;131.0;;Docume...
4     Color;Andrew Stanton;462.0;132.0;475.0;530.0;S...
...                                                 ...
4910  Color;Scott Smith;1.0;87.0;2.0;318.0;Daphne Zu...
4911  Color;;43.0;43.0;;319.0;Valorie Curry;841.0;;C...
4912  Color;Benjamin Roberds;13.0;76.0;0.0;0.0;Maxwe...
4913  Color;Daniel Hsia;14.0;100.0;0.0;489.0;Daniel ...
4914  Color;Jon Gunn;43.0;90.0;16.0;16.0;Brian Herzl...

[4915 rows x 1 columns]

In [8]:
columns: List[str] = ['color','director_name','num_critic_for_reviews','duration','director_facebook_likes','actor_3_facebook_likes','actor_2_name','actor_1_facebook_likes','gross','genres','actor_1_name','movie_title','num_voted_users','cast_total_facebook_likes','actor_3_name','facenumber_in_poster','plot_keywords','movie_imdb_link','num_user_for_reviews','language','country','content_rating','budget','title_year','actor_2_facebook_likes','imdb_score','aspect_ratio','movie_facebook_likes']


movie: pd.DataFrame = pd.read_csv('movie_new.csv', sep=';', names=columns)

movie_num: pd.DataFrame = movie.select_dtypes(include=['float', 'int'])

di: Dict[str, float] = {}
    
for i in movie_num.columns:
    di[str(i)] = movie_num[i].sum() / movie_num.index.stop

movie_num: pd.DataFrame = movie_num.fillna(di)

###############################
sdv: float = 0

for i in movie_num.columns:
    if sdv < movie_num[i].std():
        sdv = movie_num[i].std()
sdv

################################

for i in movie_num.columns:
    movie[i] = movie_num[i]

################################
di2: Dict[str, str] = {}

for i in movie.columns:
    di2[str(i)] = movie[str(i)].iloc[0]

movie: pd.DataFrame = movie.fillna(di2) 

################################

col_rename: Dict[str, str]={
    'director_name': 'rezyser'
}

movie: pd.DataFrame = movie.rename(columns=col_rename)

################################

movie['imdb_score'] += 1

################################
col_rename2: Dict[str, str]={}

for i in movie.columns:
    col_rename2[i] = i.casefold().capitalize()

col_rename2

movie: pd.DataFrame = movie.rename(columns = col_rename2)

################################
a: int = 0
b: int = 0

while a >= b:
    a = np.random.randint(50)
    b = np.random.randint(50)

movie_random: pd.DataFrame = movie.iloc[a:b, :]
movie_random

################################

movie_num2: pd.DataFrame = movie.select_dtypes(include=['int','float'])

pd.options.mode.chained_assignment = None    
    
for i in movie_num2.columns:
    movie_num2[i] = movie_num2[i] + np.random.randint(100)

movie_num2

,Num_critic_for_reviews,Duration,Director_facebook_likes,Actor_3_facebook_likes,Actor_1_facebook_likes,Gross,Budget,Title_year,Actor_2_facebook_likes,Imdb_score,Aspect_ratio,Movie_facebook_likes
0,765.000000,217.000000,62.000000,890.000000,1032.0,7.605059e+08,2.370000e+08,2054.000000,977.0,16.9,2.780000,33058.0
1,344.000000,208.000000,625.000000,1035.000000,40032.0,3.094042e+08,3.000000e+08,2052.000000,5041.0,16.1,3.350000,58.0
2,644.000000,187.000000,62.000000,196.000000,11032.0,2.000742e+08,2.450000e+08,2060.000000,434.0,15.8,3.350000,85058.0
3,855.000000,203.000000,22062.000000,23035.000000,27032.0,4.481307e+08,2.500000e+08,2057.000000,23041.0,17.5,3.350000,164058.0
4,178.613507,145.764036,193.000000,663.322823,163.0,3.929030e+07,3.294924e+07,2044.544548,53.0,16.1,3.072819,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4911,43.000000,126.000000,64.000000,353.000000,669.0,3.929030e+07,3.294924e+07,2058.000000,511.0,16.7,3.072819,142.0
4912,85.000000,82.000000,738.676973,354.000000,873.0,3.929030e+07,3.294924e+07,2044.544548,634.0,16.5,17.000000,32058.0
4913,55.000000,115.000000,62.000000,35.000000,32.0,3.929030e+07,1.441000e+03,2058.000000,41.0,15.3,3.072819,74.0
4914,56.000000,139.000000,62.000000,524.000000,978.0,1.049300e+04,3.294924e+07,2057.000000,760.0,15.3,3.350000,718.0
4915,85.000000,129.000000,78.000000,51.000000,118.0,8.527200e+04,1.141000e+03,2049.000000,64.0,15.6,2.850000,514.0